const DiagnosticData = [
    "Cholesterol",
    "HDL",
    "Triglyceride",
    "Lipid Profile",
    "Uric Acid",
    "Bilirubin",
    "SGPT",
    "SGOT",
    "ALP",
    "LFT",
    "NA K CL",
    "Calcium",
    "Magnesium",
    "Amylase",
    "Lipase",
    "CPK",
    "CPK MB",
    "BUN",
    "Troponin -T",
    "TC",
    "DC",
    "ESR",
    "HB",
    "PCV",
    "PLATELET",
    "HB TC DC",
    "Hb TC DC ESR",
    "BT CT",
    "COMPLETE HAEMOGRAM",
    "Reticulocyte Count",
    "Prothombin Time",
    "APTT",
    "Blood Grouping",
    "Absolute Eosinophil count",
    "MP Slide",
    "MP Ag",
    "Direct coombs Test",
    "Indirect coombs Test",
    "D Dimer",
    "VIT B12",
    "ANTI CCP",
    "HEV Antibody lgG",
    "HEV Antibody lgM",
    "HCO3",
    "HCV Genotype",
    "HBsab",
    "HBeAg",
    "HAV lgM",
    "TB Gold",
    "CGFR",
    "E2",
    "E3",
    "C-peptide Level",
    "Calcitonin",
    "ADA",
    "ADH",
    "ACE",
    "AFP",
    "CARCINO EMBRYONIC ANTIGEN",
    // "ADA",
    // "ADH",
    "GAMMA GT",
    "GLYCOSOLATED HAEMOGLOBIN",
    "HB.Electrophoresis",
    "Allergy profile",
    "TSH",
    "FT4.TSH",
    "T3 T4 TSH",
    "LH",
    "FSH",
    "T3",
    "T4",
    "PROLACTIN",
    "FT4",
    "FT3",
    "PSA",
    "TESTOSTERONE",
    "CELL COUNT + TYPE",
    "CA 15.3",
    "Vit D3/25 OH",
    "SERUM lgE",
    "TOXO lgM",
    "TOXO lgG",
    "Torch",
    "AMH",
    "ESTRADIOL",
    "BETA HCG",
    "CA 125",
    "FERRITIN",
    "ANA ANF HEP 2",
    "PROGESTERONE",
    "G6PD",
    "INSULIN",
    "IRON",
    "TIBC",
    "CORTISOL",
    "Microalbumin",
    "HLA B27 EDTA",
    "HLA B27 PCR",
  ];
  export default DiagnosticData;